Eliminate leading tabs

diff --git a/capitalize-tags b/capitalize-tags
--- a/capitalize-tags
+++ b/capitalize-tags
@@ -13,21 +13,21 @@ readonly __base="$(basename "${__file}" .sh)"
 
 invalid="false"
 for flacfile in "${@}"; do
-	# We must use process substitution for this loop (instead of a pipe).
-	# Otherwise the "continue" will not work, since the pipe runs in a subprocess.
-	tempfile=$(mktemp)
+    # We must use process substitution for this loop (instead of a pipe).
+    # Otherwise the "continue" will not work, since the pipe runs in a subprocess.
+    tempfile=$(mktemp)
     while read -r tagline; do
-		if [[ "${tagline}" == *=*  ]]; then
-			tagname="${tagline%%=*}"
-			tagvalue="${tagline#*=}"
-			printf '%s=%s\n' "${tagname@U}" "${tagvalue}" >> "${tempfile}"
-		else
-			echo "${flacfile}: Unable to process multiline tag \"${tagname}\"" | colorize red >&2
-			rm -f "${tempfile}" || true
-			continue 2
-		fi
+        if [[ "${tagline}" == *=*  ]]; then
+            tagname="${tagline%%=*}"
+            tagvalue="${tagline#*=}"
+            printf '%s=%s\n' "${tagname@U}" "${tagvalue}" >> "${tempfile}"
+        else
+            echo "${flacfile}: Unable to process multiline tag \"${tagname}\"" | colorize red >&2
+            rm -f "${tempfile}" || true
+            continue 2
+        fi
     done < <(metaflac --export-tags-to=- "${flacfile}")
-	echo "${flacfile}: Rewriting capitalized tags ..."
-	metaflac --remove-all-tags --import-tags-from="${tempfile}" "${flacfile}"
-	rm -f "${tempfile}" || true
+    echo "${flacfile}: Rewriting capitalized tags ..."
+    metaflac --remove-all-tags --import-tags-from="${tempfile}" "${flacfile}"
+    rm -f "${tempfile}" || true
 done
diff --git a/check-album b/check-album
--- a/check-album
+++ b/check-album
@@ -77,9 +77,9 @@ while true; do
     shift
 done
 if (( $# != 1 )); then
-	echo "Error: Invalid parameters specified!" >&2
-	show_help >&2
-	exit 2
+    echo "Error: Invalid parameters specified!" >&2
+    show_help >&2
+    exit 2
 fi
 PARAMETERS=("$@")
 TARGETDIR="${1}"
@@ -90,19 +90,19 @@ pushd "${TARGETDIR}" >/dev/null 2>&1
 # Check if a SHA256 file exists and validate the files
 echo "Validating file integrity:" | colorize blue
 if compgen -G "*.sha256" >/dev/null 2>&1; then
-	sha256sum -c *.sha256 || {
-		echo "=> Validation failure <=" | colorize red >&2
-		if ${autofix:-"false"} && ! ${force:-"false"}; then
-			echo "Aborting: Will not fix unvalidated files unless forced!" | colorize red >&2
-			exit 99
-		fi
-	}
-	}
+    sha256sum -c *.sha256 || {
+        echo "=> Validation failure <=" | colorize red >&2
+        if ${autofix:-"false"} && ! ${force:-"false"}; then
+            echo "Aborting: Will not fix unvalidated files unless forced!" | colorize red >&2
+            exit 99
+        fi
+    }
+    }
 
-	# TODO: Check if SHA file lists all flac files
-	# TODO: Check if SHA file contains additional files
+    # TODO: Check if SHA file lists all flac files
+    # TODO: Check if SHA file contains additional files
 else
-	echo "=> There is no hashfile <=" | colorize red >&2
+    echo "=> There is no hashfile <=" | colorize red >&2
 fi
 
 # Capitalize all tag names
@@ -110,8 +110,8 @@ echo "Checking tag capitalization:" | colorize blue
 invalid_tags="false"
 ${__dir}/check-tags-capitalized *.flac || invalid_tags="true"
 if ${invalid_tags:-"false"} && ${autofix:-"false"} || ${force:-"false"}; then
-	echo "Capitalizing tags:" | colorize blue
-	${__dir}/capitalize-tags *.flac
+    echo "Capitalizing tags:" | colorize blue
+    ${__dir}/capitalize-tags *.flac
 fi
 
 
@@ -129,8 +129,8 @@ echo "Checking ReplayGain information:" | colorize blue
 invalid_replaygain="false"
 ${__dir}/check-tags-replaygain *.flac || invalid_replaygain="true"
 if ${invalid_replaygain:-"false"} && ${autofix:-"false"} || ${force:-"false"}; then
-	echo "Adding ReplayGain info:" | colorize blue
-	${__dir}/add-replaygain-tags *.flac
+    echo "Adding ReplayGain info:" | colorize blue
+    ${__dir}/add-replaygain-tags *.flac
 fi
 metaflac --show-tag=REPLAYGAIN_TRACK_GAIN --show-tag=REPLAYGAIN_ALBUM_GAIN --show-tag=REPLAYGAIN_TRACK_PEAK --show-tag=REPLAYGAIN_ALBUM_PEAK *.flac
 
@@ -139,15 +139,15 @@ metaflac --show-tag=REPLAYGAIN_TRACK_GAIN --show-tag=REPLAYGAIN_ALBUM_GAIN --sho
 # TODO: Check if filenames are OK: Format %artist%
 
 if ${autofix:-"false"} || ${force:-"false"}; then
-	echo "Sorting and merging padding:" | colorize blue
-	metaflac --sort-padding *.flac
-	echo "Done"
+    echo "Sorting and merging padding:" | colorize blue
+    metaflac --sort-padding *.flac
+    echo "Done"
 fi
 
 # When we are done, check if recreation of the SHA256 file is required
 if ! sha256sum -c *.sha256 >/dev/null 2>&1 && ${autofix:-"false"} || ${force:-"false"}; then
-	echo "Creating hash file:" | colorize blue
-	${__dir}/create-hashfile *.flac
+    echo "Creating hash file:" | colorize blue
+    ${__dir}/create-hashfile *.flac
 fi
 
 popd >/dev/null 2>&1
diff --git a/check-tags-replaygain b/check-tags-replaygain
--- a/check-tags-replaygain
+++ b/check-tags-replaygain
@@ -13,18 +13,18 @@ readonly __base="$(basename "${__file}" .sh)"
 
 is_invalid="false"
 for flacfile in "${@}"; do
-	track_gain=$(get_tag_value REPLAYGAIN_TRACK_GAIN "${flacfile}") || true
-	track_peak=$(get_tag_value REPLAYGAIN_TRACK_PEAK "${flacfile}") || true
-	album_gain=$(get_tag_value REPLAYGAIN_ALBUM_GAIN "${flacfile}") || true
-	album_peak=$(get_tag_value REPLAYGAIN_ALBUM_PEAK "${flacfile}") || true
-	# echo "ReplayGain for $flacfile = $track_gain / $album_gain"
-	# TODO: check the REPLAYGAIN_ALBUM_GAIN + REPLAYGAIN_ALBUM_PEAK match between all files
-	if [[ -z ${track_gain} || -z ${track_peak} || -z ${album_gain} || -z ${album_peak} ]]; then
-		is_invalid="true"
-		echo "=> ${flacfile}: ReplayGain information is missing or incorrect <=" | colorize red >&2
-	fi
+    track_gain=$(get_tag_value REPLAYGAIN_TRACK_GAIN "${flacfile}") || true
+    track_peak=$(get_tag_value REPLAYGAIN_TRACK_PEAK "${flacfile}") || true
+    album_gain=$(get_tag_value REPLAYGAIN_ALBUM_GAIN "${flacfile}") || true
+    album_peak=$(get_tag_value REPLAYGAIN_ALBUM_PEAK "${flacfile}") || true
+    # echo "ReplayGain for $flacfile = $track_gain / $album_gain"
+    # TODO: check the REPLAYGAIN_ALBUM_GAIN + REPLAYGAIN_ALBUM_PEAK match between all files
+    if [[ -z ${track_gain} || -z ${track_peak} || -z ${album_gain} || -z ${album_peak} ]]; then
+        is_invalid="true"
+        echo "=> ${flacfile}: ReplayGain information is missing or incorrect <=" | colorize red >&2
+    fi
 done
 
 if ${is_invalid:-"false"}; then
-	exit 1
+    exit 1
 fi
